

persistence:
  main:
    jdbcUrl: jdbc:mysql://localhost:3306/socialnetwork
    username: root
    password: root
  replica:
    jdbcUrl: jdbc:mysql://localhost:3308/socialnetwork
    username: root
    password: root
#logging.level.org.springframework.jdbc.core.JdbcTemplate=trace
#logging.level.org.springframework.jdbc.core=TRACE
opentracing:
    jaeger:
      service-name: OpenTracingAPIApp
      enabled: true
      udp-sender:
        host: localhost
