services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 61613:61613
      - 15672:15672
  redis:
    image: redis
    ports:
      - 6379:6379
#  kong:
#      image: kong
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411


  jaeger:
    image: jaegertracing/all-in-one:1.42
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411


#  mysql-main:
#    image: mysql/mysql-server:5.7.37
#    ports:
#      - 3309:3309
