services:
  mysql-main:
    image: mysql/mysql-server:5.7.37
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: socialnetwork
    ports:
      - 3306:3306
    networks:
      - mysql
    volumes:
      - ./mysql-main/my.cfg:/etc/my.cfg
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 61613:61613
      - 15672:15672
  redis:
    image: redis
    ports:
      - 6379:6379
  tarantool-np:
    build: ./tarantool
    volumes:
      - ./tarantool/volume:/var/lib/tarantool
    networks:
      - mysql
    ports:
      - 3301:3301
  tarantool-replication-con:
    build: ./tarantool replication
    networks:
      - mysql
  jaeger:
    image: jaegertracing/all-in-one:1.42
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
networks:
  mysql:
    external: true
    name: mysql
