{
 "title": "Chat API metrics Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Rate ",
   "type": "timeseries",
   "description": "Rate of requests per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Summ of different errors - 500,404, in-app",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(logback_events_total{level=\"error\"})",
     "legendFormat": "In-app errors {{label_name}}"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"404\"})",
     "legendFormat": "404 ERRORS"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{status=\"500\"})",
     "legendFormat": "500  ERRORS"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": " average inbound request duration across all tags",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate( http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM_MEMORY_USED",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}